Logging code
ssl-hep/ServiceX_App pull request #142
Opened 2021-10-14 18:05 UTC by sthapa

Apparently this didn't get merged before, submitting a PR now

2021-10-15 15:49 UTC, BenGalewsky commented on servicex/resources/add_file_to_dataset.py
> +    def __init__(self):
Could this be moved to `ServiceXResource`?

2021-10-15 15:50 UTC, BenGalewsky commented on servicex/resources/all_transformation_requests.py
> +            self.logger.info(f"Querying transform request by id: {query_id}")
Is this really worthy of a `.info` log message?

2021-10-15 15:54 UTC, BenGalewsky commented on servicex/resources/transform_status.py
> -            print("+--------------------------------------------+")
Going to miss this, but yeah - it doesn't make sense in Kabana!

2021-10-15 15:55 UTC, BenGalewsky requested changes
This is great! Please see if the logger initialization can be moved to the `ServiceXResource` base class constructor

2021-10-15 20:14 UTC, sthapa commented
@BenGalewsky  Changes made, can you review again?

2021-10-15 20:30 UTC, BenGalewsky requested changes
Is there a reason the logger init code is still in several of the resource sub classes?

2021-10-15 20:30 UTC, BenGalewsky commented on servicex/resources/all_transformation_requests.py
> +    def __init__(self):
Should this still be here?

2021-10-15 20:30 UTC, BenGalewsky commented on servicex/resources/deployment_status.py
> +        Initialize object
Should this still be here?

2021-10-16 17:56 UTC, BenGalewsky commented
Looks like the tests are failing. Let me know if you need help clearing those up.

2021-10-18 20:12 UTC, sthapa commented
@BenGalewsky, can you review again?

2021-10-18 20:32 UTC, AndrewEckart commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
I think the idiomatic way to log an exception with traceback is:
```
except Exception as e:
    logging.error(e, exc_info=True)
```

2021-10-18 20:36 UTC, AndrewEckart commented on servicex/web/transformation_request.py
> +    current_app.logger.info(f"Got transformation request: {id_}")
This will log whenever people visit the webpage for a specific transformation request. I don't think we really need to log this since it will already be covered by the standard HTTP server logs.

2021-10-19 18:39 UTC, sthapa commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
I don't see what the logging.error call gives us that the logging.exception call doesn't and the exception call potentially adds better exception logging down the road.

2021-10-19 18:40 UTC, AndrewEckart commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
I think they are effectively the same, I was more referring to `exc_info=True` which produces the traceback.

2021-10-19 18:44 UTC, sthapa commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
The exception prints a traceback automatically.

2021-10-19 18:45 UTC, AndrewEckart commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
Nevermind, I misunderstood how `logger.exception` works. It seems like the way you have it will produce a full traceback.

2021-10-19 18:46 UTC, sthapa commented on servicex/web/transformation_request.py
> +    current_app.logger.info(f"Got transformation request: {id_}")
Changed to debug level, I'd argue that the id in our logging format will make it easier to ingest and query in kibana

2021-10-19 19:04 UTC, sthapa commented on servicex/resources/preflight_check.py
> +            self.logger.exception("Got exception in pre-flight check")
Ok, resolving

2021-10-19 19:24 UTC, BenGalewsky approved these changes
Got there in the end!

2021-10-19 19:25 UTC, BenGalewsky commented
@AndrewEckart - Are you still awaiting changes?

2021-10-19 19:25 UTC, AndrewEckart commented
> @AndrewEckart - Are you still awaiting changes?

No, please merge!

2021-10-19 19:30 UTC, BenGalewsky commented
@sthapa oops look like you got gazumped by @AndrewEckart s changes to `TransformRequest` database methods. You have merge conflicts. Please resolve

2021-10-19 20:11 UTC, merged

2021-10-19 20:14 UTC, AndrewEckart commented
> @sthapa oops look like you got gazumped by @AndrewEckart s changes to `TransformRequest` database methods. You have merge conflicts. Please resolve

Standard "rebase and merge" led to conflicts that had been fixed in later commits, so a "squash and merge" took care of them.