Added parameters to top level json result
ssl-hep/ServiceX_App pull request #181
Opened 2022-07-22 16:23 UTC by jakel2014

### Problem

Performance of ServiceX Jupyterlab plugin is limited due to the absence of certain parameters in the top level json result.
Potential solution to [Lab Extension Issue 3](https://github.com/ssl-hep/servicex-labextension/issues/3)

### Approach

Added parameters to object that is returned in function to_json in servicex/models.py, which ends up being used to create the top level json result.

### Testing

The top level json result should now contain 5 additional parameters (submit-time, finish-time, files-processed, files-remaining, files-skipped)

2022-09-20 13:50 UTC, alexander-held commented
Hi @BenGalewsky, @ivukotic, could we please get this merged (after #180) to more easily allow for the use of @jakel2014's JupyterLab extension?

2022-09-21 14:39 UTC, ivukotic requested changes
why moving to psycopg2-binary? 

As written [here](https://www.psycopg.org/docs/install.html#:~:text=psycopg%20vs%20psycopg%2Dbinary,binary%20as%20a%20module%20dependency.): 
The psycopg2-binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.

If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.

2022-09-22 21:05 UTC, BenGalewsky commented
> why moving to psycopg2-binary?

That was my accident. I use it in my development environment. Jake picked up my commits from PR #180 (which you merged!) 

I'll remove my commits from this PR (and fix that lib in develop)

2022-09-22 21:09 UTC, BenGalewsky commented
Moved to #185

2022-09-22 21:09 UTC, closed without merging